"""
Django settings for smart_agri project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^vn@=au#52dzhwvk=droi7nzrk8qmiink^dof9zy*5a!$gz$ij"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# .loca.lt is here only for the temporary `npx localtunnel` used to demo QR
# pairing from a phone before real robot hardware exists. Remove it, and
# localhost/127.0.0.1 with it, once that's no longer needed - Django only
# auto-allows those two for a bare `ALLOWED_HOSTS = []`, and setting the list
# explicitly like this opts out of that default.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".loca.lt"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third Party Apps
    "rest_framework",
    "corsheaders",

    # Local Apps
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smart_agri.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "smart_agri.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django REST Framework
# https://www.django-rest-framework.org/
from datetime import timedelta  # noqa: E402

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    # Locked by default: nothing is readable without signing in. Most
    # endpoints tighten this further to core.permissions.IsAdmin; the few
    # public ones (login, QR pair lookup) opt out explicitly.
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Only the "Forgot password" endpoints opt in (ScopedRateThrottle), so a
    # stranger can't spam someone's inbox or hammer the code check.
    "DEFAULT_THROTTLE_RATES": {
        "password_reset": "10/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# CORS - allow the Vite dev server to call the API from the browser. Vite
# falls back to the next free port (5174, 5175, ...) whenever 5173 is already
# taken by another running instance, so a small range is allowed rather than
# just the default port.
CORS_ALLOWED_ORIGINS = [
    f"http://{host}:{port}"
    for host in ("localhost", "127.0.0.1")
    for port in range(5173, 5178)
]

# WeatherAPI.com - the forecast half of the advisory engine. Free tier is
# 1M calls/month and 3 forecast days, which is all the rules look at.
# Grab a key at https://www.weatherapi.com/ and export it before runserver:
#     PowerShell:  $env:WEATHERAPI_KEY = "your-key"
#     bash:        export WEATHERAPI_KEY=your-key
# Without a key the advisory still runs - it just falls back to whatever
# weather rows are already in the database, or skips the weather rules.
WEATHERAPI_KEY = os.environ.get("WEATHERAPI_KEY", "")
WEATHERAPI_BASE_URL = "https://api.weatherapi.com/v1"
# Don't re-hit the API if the farm already has a reading this fresh.
WEATHER_CACHE_MINUTES = 30

# Email - used for "Forgot password" codes. Set EMAIL_HOST (plus user and
# password) to send real mail over SMTP. Without it, emails are printed to
# the runserver terminal instead, which is handy while developing.
#     PowerShell:  $env:EMAIL_HOST = "smtp.gmail.com"; $env:EMAIL_HOST_USER = "..."; $env:EMAIL_HOST_PASSWORD = "..."
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "Smart Agriculture <no-reply@smartagri.local>"
)
