# Generated by Django 6.0.6 on 2026-07-23 06:24

from django.db import migrations


def fix_em_dash(apps, schema_editor):
    RobotHistory = apps.get_model("core", "RobotHistory")
    RobotHistory.objects.filter(farmer="—").update(farmer="-")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fix_em_dash, migrations.RunPython.noop),
    ]
