# Generated by Django 6.0.6 on 2026-08-03 11:55

import secrets

from django.db import migrations, models
from django.utils import timezone


def issue_pair_tokens(apps, schema_editor):
    """Give every unclaimed robot a QR token.

    Robots the admin already handed to a farmer count as claimed - otherwise
    anyone scanning their sticker could take them off that farmer.
    """
    Robot = apps.get_model("core", "Robot")
    now = timezone.now()
    for robot in Robot.objects.all():
        if (robot.farmer or "").strip():
            robot.paired_at = now
            robot.pair_token = ""
        else:
            robot.pair_token = secrets.token_urlsafe(24)
        robot.save(update_fields=["paired_at", "pair_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_farmer_auth_user_farmer_status_alter_farmer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="pair_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="paired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(issue_pair_tokens, migrations.RunPython.noop),
    ]
