# Generated by Django 6.0.6 on 2026-08-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_robot_pair_token_robot_paired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rule_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Dismissed", "Dismissed"),
                    ("Done", "Done"),
                ],
                default="New",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.recommendation",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[("Manual", "Manual"), ("Advisory", "Advisory")],
                default="Manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("Irrigation", "Irrigation"),
                    ("Fertilizer", "Fertilizer"),
                    ("Inspection", "Inspection"),
                    ("Maintenance", "Maintenance"),
                    ("Harvest", "Harvest"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="weather",
            name="forecast",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="robot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.robot",
            ),
        ),
    ]
