# Generated by Django 6.0.6 on 2026-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recommendation_details_recommendation_rule_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority_score", "due_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="task",
            name="fertilizer_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="water_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
