# Generated by Django 6.0.6 on 2026-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_task_options_task_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
