# Generated by Django 6.0.6 on 2026-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_task_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendation",
            options={"ordering": ["-priority_score", "-created_at"]},
        ),
        migrations.AddField(
            model_name="recommendation",
            name="priority_score",
            field=models.IntegerField(default=0),
        ),
    ]
