# Generated by Django 6.0.6 on 2026-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_recommendation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="device_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
