# Generated by Django 6.0.6 on 2026-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_staff_profile_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="notify_robot_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="notify_task_assignments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("employee", "Employee")],
                default="admin",
                max_length=20,
            ),
        ),
    ]
